name: daos2

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout spack
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -q -y \
          build-essential \
          clang \
          clang-format \
          cmake \
          curl \
          fuse3 \
          git \
          golang-go \
          kmod \
          libaio-dev \
          libboost-dev \
          libcmocka-dev \
          libcunit1-dev \
          libfuse3-dev \
          libhwloc-dev \
          libibverbs-dev \
          libjson-c-dev \
          liblz4-dev \
          libnuma-dev \
          libmd-dev \
          libmpich-dev \
          libprotobuf-c-dev \
          librdmacm-dev \
          libssl-dev \
          libtool-bin \
          libunwind-dev \
          libyaml-dev \
          locales \
          maven \
          mpich \
          numactl \
          openjdk-8-jdk \
          patchelf \
          pciutils \
          pkg-config \
          python3-dev \
          python3-venv \
          uuid-dev \
          valgrind \
          yasm
    - name: Run a multi-line script
      run: |
        . ./share/spack/setup-env.sh
        spack spec daos2 ^protobuf-c@1.4.1 ^protobuf@3.21.12 ^python@3.10.6
        spack install -v --show-log-on-error daos2 \
        ^protobuf-c@1.4.1 ^protobuf@3.21.12 ^python@3.10.6

