name: daos2

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout spack
      uses: actions/checkout@v3
    - name: Run a multi-line script
      run: |
        . ./share/spack/setup-env.sh
        spack install py-pip
        spack load py-pip
        which pip
        spack install -v --show-log-on-error daos2 ^protobuf-c@1.4.1 ^protobuf@3.21.12
        
