name: daos apt install deps

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -q -y \
        autoconf \
        build-essential \
        clang \
        clang-format \
        cmake \
        curl \
        fuse3 \
        git \
        golang-go \
        kmod \
        libaio-dev \
        libboost-dev \
        libcmocka-dev \
        libcunit1-dev \
        libfuse3-dev \
        libhwloc-dev \
        libibverbs-dev \
        libipmctl-dev \        
        libjson-c-dev \
        liblz4-dev \
        libnuma-dev \
        libmd-dev \
        libmpich-dev \
        libprotobuf-c-dev \
        librdmacm-dev \
        libssl-dev \
        libtool-bin \
        libunwind-dev \
        libyaml-dev \
        locales \
        maven \
        mpich \
        numactl \
        openjdk-8-jdk \
        patchelf \
        pciutils \
        pkg-config \
        python3-dev \
        python3-venv \
        uuid-dev \
        valgrind \
        yasm
    - name: Checkout spack
      uses: actions/checkout@v3
    - name: Run a multi-line script
      run: |
        . ./share/spack/setup-env.sh
        spack spec daos \
        ^go@1.19.5 ^protobuf-c@1.4.1 ^protobuf@3.21.12 ^spdk@23.01
        spack install -v --show-log-on-error daos \
        ^go@1.19.5 ^protobuf-c@1.4.1 ^protobuf@3.21.12 ^spdk@23.01
        
