name: h5py

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install
      run: |
        . ./share/spack/setup-env.sh
        spack compiler find
        spack external find
        spack spec py-h5py@master+mpi
        cp ./var/spack/repos/builtin/packages/py_h5py/package.py /home/runner/.spack/package_repos/*/repos/spack_repo/builtin/packages/py_h5py/package.py
        spack install py-h5py@master+mpi ^hdf5@develop-2.0
        spack install py-pytest
        spack install py-pip
        spack install py-pytest-mpi
        spack install py-ipython
        spack load py-h5py
        spack load py-pytest
        spack load py-pip
        spack load py-pytest-mpi
        spack load py-ipython
        python -c "import h5py; h5py.run_tests(); print(h5py.version.info);"
