name: mac hdf5@1.12.2+mpi+fortran

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout spack
      uses: actions/checkout@v3
    - name: Run a multi-line script
      run: |
        . ./share/spack/setup-env.sh
        spack spec hdf5@1.12.2+mpi+fortran
        spack install hdf5@1.12.2+mpi+fortran
      