name: py-jarvis-util

on:
  push:
    branches: [ develop- ]
  pull_request:
    branches: [ develop- ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout spack
      uses: actions/checkout@v3
    - name: Spack install py-jarvis-util
      run: |
        . ./share/spack/setup-env.sh
        spack spec py-jarvis-util
        spack install py-jarvis-util
