name: spack ubuntu

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout spack
      uses: actions/checkout@v2

    - name: Run a multi-line script
      run: |
        . ./share/spack/setup-env.sh
        spack repo add .
        spack repo list
        spack install hdf5-av
        spack install hdf-async
        
