name: spack ubuntu

on:
  push:
    branches: [ develop- ]
  pull_request:
    branches: [ develop- ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout spack
      uses: actions/checkout@v2
    - name: Install GDS/CUDA
      run: |
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.0-1_all.deb
        sudo dpkg -i cuda-keyring_1.0-1_all.deb
        sudo apt-get update
        sudo apt-get install -y cuda-nvcc-11-8 libcufile-dev-11-8
        echo "PATH=/usr/local/cuda/bin${PATH:+:${PATH}}" >> $GITHUB_ENV
        echo "CUDA_PATH=/usr/local/cuda" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=/usr/local/lib:/usr/local/cuda/lib64:${LD_LIBRARY_PATH}" >> $GITHUB_ENV   

    - name: Run a multi-line script
      env:
        CUDACXX: /usr/local/cuda-11.5/bin/nvcc
      run: |
        . ./share/spack/setup-env.sh
        # export HDF5_VOL_CONNECTOR="ADIOS2_VOL"
        # spack install hdf5-examples
        # spack install hdf5-vol-async
        # spack install --test root adios2@master+shared+hdf5 ^hdf5@develop-1.13
        spack install --test root hdf5-vfd-gds
