name: spack ubuntu

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout spack
      uses: actions/checkout@v2
    - name: Install GDS/CUDA
      run: |
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
        sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
        sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
        sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"
        sudo apt-get update
        sudo apt-get -y install cuda

    - name: Run a multi-line script
      run: |
        . ./share/spack/setup-env.sh
        # export HDF5_VOL_CONNECTOR="ADIOS2_VOL"
        # spack install hdf5-examples
        # spack install hdf5-vol-async
        # spack install --test root hdf5-cmake@jhendersonHDF.H5FD_dynamic+vfd-gds
        # spack install --test root adios2@master+shared+hdf5 ^hdf5@develop-1.13
        spack install --test root hdf5-vfd-gds