name: hdf5-vol-daos

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout spack
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        wget https://raw.githubusercontent.com/daos-stack/daos/master/utils/scripts/install-ubuntu.sh        
        chmod u+x install-ubuntu.sh
        sudo ./install-ubuntu.sh
    - name: Run a multi-line script
      run: |
        . ./share/spack/setup-env.sh
        spack spec hdf5-vol-daos
        # spack spec hdf5-vol-daos \
        # ^dpdk@main ^go@1.19.5 ^protobuf-c@1.4.1 ^protobuf@3.21.12 ^python@3.10.6 
        # spack install -v --show-log-on-error hdf5-vol-daos \
        # ^dpdk@main ^go@1.19.5 ^protobuf-c@1.4.1 ^protobuf@3.21.12 ^python@3.10.6

